version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform Intersight Policies - Certificate Management
  Manages Intersight Certificate Management Policies
  
  Location in GUI:
  `Policies` » `Create Policy` » `Certificate Management`
  
  ## Example

  ### main.tf
  ```hcl
  {{ include "examples/complete/main.tf" }}
  ```

  ### variables.tf
  ```hcl
  {{ include "examples/complete/variables.tf" }}
  ```

  ### versions.tf
  ```hcl
  {{ include "examples/complete/versions.tf" }}
  ```

  ## Environment Variables

  ## Terraform Cloud/Enterprise - Workspace Variables
  - Add variable apikey with value of [your-api-key]
  - Add variable base64_certificate with value of [your-base64_certificate]
  - Add variable base64_private_key with value of [your-base64_private_key]
  - Add variable secretkey with value of [your-secret-file-content]

  ## Linux
  ```bash
  export TF_VAR_apikey="<your-api-key>"
  export TF_VAR_base64_certificate=`cat <your-base64_certificate>`
  export TF_VAR_base64_private_key=`cat <your-base64_private_key>`
  export TF_VAR_secretkey=`cat <secret-key-file-location>`
  ```

  ## Windows
  ```bash
  $env:TF_VAR_apikey="<your-api-key>"
  $env:TF_VAR_base64_certificate="<your-base64_certificate>"
  $env:TF_VAR_base64_private_key="<your-base64_private_key>"
  $env:TF_VAR_secretkey="<secret-key-file-location>"
  ```


  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Resources }}
output:
  file: README.md
  mode: replace

sort:
  enabled: false